"""Type stubs for pathlibrs — a fast pure-Rust pathlib implementation."""

from collections.abc import Callable, Generator, Iterator, Sequence
from os import PathLike, stat_result
from typing import (
    IO,
    Any,
)

__all__ = [
    "PurePath",
    "PurePosixPath",
    "PureWindowsPath",
    "Path",
    "PosixPath",
    "WindowsPath",
]

class PurePath(PathLike[str]):
    """Base class for pure (non-IO) path objects."""

    parser: str

    def __new__(cls, *pathsegments: str | PathLike[str]) -> PurePath: ...
    def __init__(self, *pathsegments: str | PathLike[str]) -> None: ...
    def __bytes__(self) -> bytes: ...
    def __eq__(self, other: object) -> bool: ...
    def __fspath__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other: PurePath) -> bool: ...
    def __le__(self, other: PurePath) -> bool: ...
    def __gt__(self, other: PurePath) -> bool: ...
    def __ge__(self, other: PurePath) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __truediv__(self, key: str | PathLike[str]) -> PurePath: ...
    def __rtruediv__(self, key: str | PathLike[str]) -> PurePath: ...
    def __reduce__(self) -> tuple[Any, ...]: ...
    @property
    def anchor(self) -> str: ...
    @property
    def drive(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def parent(self) -> PurePath: ...
    @property
    def parents(self) -> Sequence[PurePath]: ...
    @property
    def parts(self) -> tuple[str, ...]: ...
    @property
    def root(self) -> str: ...
    @property
    def stem(self) -> str: ...
    @property
    def suffix(self) -> str: ...
    @property
    def suffixes(self) -> list[str]: ...
    def as_posix(self) -> str: ...
    def as_uri(self) -> str: ...
    def full_match(self, pattern: str, *, case_sensitive: bool | None = None) -> bool: ...
    def is_absolute(self) -> bool: ...
    def is_relative_to(self, other: str | PathLike[str]) -> bool: ...
    def is_reserved(self) -> bool: ...
    def joinpath(self, *args: str | PathLike[str]) -> PurePath: ...
    def match(self, pattern: str, *, case_sensitive: bool | None = None) -> bool: ...
    def relative_to(self, other: str | PathLike[str], *, walk_up: bool = False) -> PurePath: ...
    def with_name(self, name: str) -> PurePath: ...
    def with_segments(self, *pathsegments: str | PathLike[str]) -> PurePath: ...
    def with_stem(self, stem: str) -> PurePath: ...
    def with_suffix(self, suffix: str) -> PurePath: ...

class PurePosixPath(PurePath):
    """Pure path subtype for POSIX systems."""

class PureWindowsPath(PurePath):
    """Pure path subtype for Windows systems."""

class Path(PurePath):
    """PurePath subclass that can make system calls."""

    def absolute(self) -> Path: ...
    def chmod(self, mode: int, *, follow_symlinks: bool = True) -> None: ...
    def copy(
        self,
        target: str | PathLike[str],
        *,
        follow_symlinks: bool = True,
        dirs_exist_ok: bool = False,
        preserve_metadata: bool = False,
        ignore: Callable[[str, list[str]], set[str]] | None = None,
        on_error: Callable[[OSError], object] | None = None,
    ) -> None: ...
    def copy_into(
        self,
        target_dir: str | PathLike[str],
        *,
        follow_symlinks: bool = True,
        dirs_exist_ok: bool = False,
        preserve_metadata: bool = False,
        ignore: Callable[[str, list[str]], set[str]] | None = None,
        on_error: Callable[[OSError], object] | None = None,
    ) -> None: ...
    @classmethod
    def cwd(cls) -> Path: ...
    def delete(self, *, ignore_errors: bool = False) -> None: ...
    def exists(self, *, follow_symlinks: bool = True) -> bool: ...
    def expanduser(self) -> Path: ...
    @classmethod
    def from_uri(cls, uri: str) -> Path: ...
    def glob(
        self,
        pattern: str,
        *,
        case_sensitive: bool | None = None,
        recurse_symlinks: bool = False,
    ) -> Generator[Path]: ...
    def group(self, *, follow_symlinks: bool = True) -> str: ...
    def hardlink_to(self, target: str | PathLike[str]) -> None: ...
    @classmethod
    def home(cls) -> Path: ...
    @property
    def info(self) -> PathInfo: ...
    def is_block_device(self) -> bool: ...
    def is_char_device(self) -> bool: ...
    def is_dir(self, *, follow_symlinks: bool = True) -> bool: ...
    def is_fifo(self) -> bool: ...
    def is_file(self, *, follow_symlinks: bool = True) -> bool: ...
    def is_junction(self) -> bool: ...
    def is_mount(self) -> bool: ...
    def is_socket(self) -> bool: ...
    def is_symlink(self) -> bool: ...
    def iterdir(self) -> Iterator[Path]: ...
    def lchmod(self, mode: int) -> None: ...
    def lstat(self) -> stat_result: ...
    def mkdir(self, mode: int = 0o777, parents: bool = False, exist_ok: bool = False) -> None: ...
    def move(
        self,
        target: str | PathLike[str],
    ) -> None: ...
    def move_into(
        self,
        target_dir: str | PathLike[str],
    ) -> None: ...
    def open(
        self,
        mode: str = "r",
        buffering: int = -1,
        encoding: str | None = None,
        errors: str | None = None,
        newline: str | None = None,
    ) -> IO: ...
    def owner(self, *, follow_symlinks: bool = True) -> str: ...
    def read_bytes(self) -> bytes: ...
    def read_text(
        self, encoding: str | None = None, errors: str | None = None, newline: str | None = None
    ) -> str: ...
    def readlink(self) -> Path: ...
    def rename(self, target: str | PathLike[str]) -> Path: ...
    def replace(self, target: str | PathLike[str]) -> Path: ...
    def resolve(self, strict: bool = False) -> Path: ...
    def rglob(
        self,
        pattern: str,
        *,
        case_sensitive: bool | None = None,
        recurse_symlinks: bool = False,
    ) -> Generator[Path]: ...
    def rmdir(self) -> None: ...
    def samefile(self, other_path: str | PathLike[str]) -> bool: ...
    def stat(self, *, follow_symlinks: bool = True) -> stat_result: ...
    def symlink_to(
        self, target: str | PathLike[str], target_is_directory: bool = False
    ) -> None: ...
    def touch(self, mode: int = 0o666, exist_ok: bool = True) -> None: ...
    def unlink(self, missing_ok: bool = False) -> None: ...
    def walk(
        self,
        top_down: bool = True,
        on_error: Callable[[OSError], object] | None = None,
        follow_symlinks: bool = False,
    ) -> Generator[tuple[Path, list[str], list[str]]]: ...
    def write_bytes(self, data: bytes) -> int: ...
    def write_text(
        self,
        data: str,
        encoding: str | None = None,
        errors: str | None = None,
        newline: str | None = None,
    ) -> int: ...

class PosixPath(Path, PurePosixPath):
    """Concrete POSIX path with filesystem operations."""

class WindowsPath(Path, PureWindowsPath):
    """Concrete Windows path with filesystem operations."""

class PathInfo:
    """Cached stat information for a path (Python 3.12+)."""

    def __init__(self, raw_path: PurePath) -> None: ...
    def exists(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def is_file(self) -> bool: ...
    def is_symlink(self) -> bool: ...
