#!/usr/bin/env python3
"""Generate .pyi type stubs for pathlibrs from the installed module.

Uses Python introspection (``__text_signature__``, ``inspect.signature``) to
produce PEP 561-compatible type stubs. Run after ``maturin develop``:

    uv run python scripts/generate_stubs.py --out stubs/
"""

from __future__ import annotations

import argparse
import inspect
import textwrap
from pathlib import Path

CLASS_HEADERS = {
    "PurePath": "class PurePath:",
    "PurePosixPath": "class PurePosixPath(PurePath):",
    "PureWindowsPath": "class PureWindowsPath(PurePath):",
    "Path": "class Path(PurePath):",
    "PosixPath": "class PosixPath(Path, PurePosixPath):",
    "WindowsPath": "class WindowsPath(Path, PureWindowsPath):",
}


CLASSES = [
    "PurePath",
    "PurePosixPath",
    "PureWindowsPath",
    "Path",
    "PosixPath",
    "WindowsPath",
]


def _is_property(cls: type, name: str) -> bool:
    """Check if an attribute is a property/descriptor (not a callable)."""
    attr = getattr(type(cls), name, None)
    if attr is None:
        return False
    if callable(attr) and not isinstance(attr, type):
        return False
    return hasattr(attr, "fget") or not callable(attr)


def _format_signature(method) -> str:
    """Extract a signature string from a method's __text_signature__ or inspect."""
    text_sig = getattr(method, "__text_signature__", None)
    if text_sig:
        return text_sig

    try:
        sig = inspect.signature(method)
        params = []
        for name, param in sig.parameters.items():
            if param.default is inspect.Parameter.empty:
                params.append(name)
            else:
                params.append(f"{name}={param.default!r}")
        return "(" + ", ".join(params) + ")"
    except (ValueError, TypeError):
        return "(...)"


def generate_stubs(output_dir: Path) -> None:
    import pathlibrs

    output_dir.mkdir(parents=True, exist_ok=True)

    init_lines = []
    init_lines.append('"""Type stubs for pathlibrs — generated by scripts/generate_stubs.py."""')
    init_lines.append("")

    stub_lines = []
    stub_lines.append(
        '"""Type stub for pathlibrs.'
        + "\n"
        + textwrap.dedent("""\
        This file is auto-generated. Do not edit manually.
        """)
        + '"""'
    )
    stub_lines.append("")

    for class_name in CLASSES:
        cls = getattr(pathlibrs, class_name)
        stub_lines.append("")
        stub_lines.append(CLASS_HEADERS[class_name])

        doc = cls.__doc__
        if doc:
            for line in doc.strip().split("\n"):
                stub_lines.append(f"    {line.strip()}")

        members: list[tuple[str, str]] = []

        for name in sorted(dir(cls)):
            if name.startswith("_") and name != "__bytes__":
                continue
            if name in {"info"}:
                continue

            attr = getattr(cls, name, None)
            if attr is None:
                continue

            if _is_property(cls, name):
                doc = getattr(type(cls).__dict__.get(name), "__doc__", None)
                doc_str = f"  # {doc.split(chr(10))[0]}" if doc else ""
                members.append(
                    (
                        name,
                        f"    @property{chr(10)}    def {name}(self) -> ...: ...{doc_str}{chr(10)}",
                    )
                )
            elif callable(attr):
                sig = _format_signature(attr)
                doc = getattr(attr, "__doc__", None)
                doc_str = f"    {chr(10)}".join(
                    f"    # {line}" for line in (doc or "").split("\n")[:1] if line.strip()
                )
                if doc_str:
                    doc_str = "\n" + doc_str
                members.append((name, f"    def {name}{sig} -> ...: ...{doc_str}\n"))

        for _, member_text in sorted(members, key=lambda x: x[0]):
            stub_lines.append(member_text)

        init_lines.append(f"from pathlibrs.pathlibrs import {class_name}")

    stub_lines.append("")

    (output_dir / "__init__.pyi").write_text("\n".join(init_lines) + "\n")
    (output_dir / "pathlibrs.pyi").write_text("\n".join(stub_lines) + "\n")

    (output_dir / "py.typed").write_text("")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate .pyi type stubs for pathlibrs.")
    parser.add_argument("--out", required=True, help="Output directory for stub files.")
    args = parser.parse_args()

    generate_stubs(Path(args.out))
    print(f"Stubs written to {args.out}/")


if __name__ == "__main__":
    main()
